-- MySQL Script generated by MySQL Workbench
-- Tue May  7 16:22:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema entregabledb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema entregabledb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entregabledb` DEFAULT CHARACTER SET utf8mb4 ;
USE `entregabledb` ;

-- -----------------------------------------------------
-- Table `entregabledb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`cursos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `cupos` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `entregabledb`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`unidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `fecha_inicion` DATE NOT NULL,
  `cursos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cursos_id`),
  INDEX `fk_unidades_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_unidades_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `entregabledb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `entregabledb`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`clases` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `visto` BINARY(1) NOT NULL,
  `unidades_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `unidades_id`),
  INDEX `fk_clases_unidades1_idx` (`unidades_id` ASC) VISIBLE,
  CONSTRAINT `fk_clases_unidades1`
    FOREIGN KEY (`unidades_id`)
    REFERENCES `entregabledb`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `entregabledb`.`bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`bloques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `visto` BINARY(1) NOT NULL,
  `clases_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `clases_id`),
  INDEX `fk_bloques_clases1_idx` (`clases_id` ASC) VISIBLE,
  CONSTRAINT `fk_bloques_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `entregabledb`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `entregabledb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categorias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `entregabledb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_categorias` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuarios_categorias_idx` (`id_categorias` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_categorias`
    FOREIGN KEY (`id_categorias`)
    REFERENCES `entregabledb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `entregabledb`.`cursos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregabledb`.`cursos_usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cursos_id` INT(11) NOT NULL,
  `usuarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_cursos_has_usuarios_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_usuarios_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `entregabledb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `entregabledb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
